### ISSUE TITLE
Add fillStyle option in the shapes 

### ISSUE THREAD

**Issue by dhruvpatidar359** [dhruvpatidar359/nextdraw#10]
**Is your feature request related to a problem? Please describe.**
Currently the shapes can be filled by the solid shape only .

**Describe the solution you'd like**
Add an extra property to change the fill style of shapes.

![image](https://github.com/dhruvpatidar359/nextdraw/assets/103873587/6e03a08e-e968-44dc-a623-4f4ee5a5261f)

**Additional context**
Element.js is the file that you have to change mainly .
Also look at the docs for rough.js , you will understand how it works.

**Comment by atharvarekhawar** [comment]
Hello @dhruvpatidar359 I already solved #11 issue and will create PR tomorrow when the event starts , and would like to contribute to this as well so can you assign this to me.

Also I had one more doubt , about how the GSSOC will know that I have contributed to this repo and this particular issue , is there some label that you add in PR or something else.

**Comment by dhruvpatidar359** [comment]
> Hello @dhruvpatidar359 I already solved #11 issue and will create PR tomorrow when the event starts , and would like to contribute to this as well so can you assign this to me.
> 
> Also I had one more doubt , about how the GSSOC will know that I have contributed to this repo and this particular issue , is there some label that you add in PR or something else.

don't worry you add the PR , it will be counted  . I will marking the PR and the issues soon.

**Comment by atharvarekhawar** [comment]
![fillStyle](https://github.com/dhruvpatidar359/nextdraw/assets/113119063/e00670af-f5ef-43a5-88e1-6cde38b07ea9)

I have completed the implementation of Fill Style option , @dhruvpatidar359 please review it and tell me if I can create a PR.

**Comment by atharvarekhawar** [comment]
also in additional context you said that element.js will be the file that will be changed mainly but I have changed only one file that is PropertiesBar.jsx , plz check into this too @dhruvpatidar359 .

**Comment by dhruvpatidar359** [comment]
> also in additional context you said that element.js will be the file that will be changed mainly but I have changed only one file that is PropertiesBar.jsx , plz check into this too @dhruvpatidar359 .

will review soon 👩‍🚀

**Comment by dhruvpatidar359** [comment]
> also in additional context you said that element.js will be the file that will be changed mainly but I have changed only one file that is PropertiesBar.jsx , plz check into this too @dhruvpatidar359 .

@atharvarekhawar  LGTM , just want to know your opinion , should we give the buttons the name of the style or should make the buttons showing that particular style . Everything else is perfecto 👩‍🚀

**Comment by atharvarekhawar** [comment]
@dhruvpatidar359 I think showing a particular style in a button is a better option

**Comment by atharvarekhawar** [comment]
@dhruvpatidar359 should I create a PR? you can change the name of the style to a design in a good first issue that will be easy for a beginner to contribute.

**Comment by dhruvpatidar359** [comment]
Hmm that seems good , you create a issue for the same . I will mark the issues with labels . Meanwhile you can create the PR
