### ISSUE TITLE
Pressing zoom out button multiple times makes the canvas see upside down

### ISSUE THREAD

**Issue by dhruvpatidar359** [dhruvpatidar359/nextdraw#11]
**Is your feature request related to a problem? Please describe.**
If you press the zoom out button again and again , the canvas will becomes upside down.

**Describe the solution you'd like**

https://github.com/dhruvpatidar359/nextdraw/assets/103873587/e6492dc2-d777-4eb6-8017-616187fd3a58

Stop the zoom out at 10% , remember it works well when you pinch and zoom.

**Additional context**

**Comment by atharvarekhawar** [comment]
Hello @dhruvpatidar359 , Great project by the way and I would love to contribute to it , can you help me setup the project locally as I am bit confused about the backend part.

**Comment by dhruvpatidar359** [comment]
Sure , I will be putting the installation guide soon

**Comment by atharvarekhawar** [comment]
I want to work on this issue, can you assign me this one , when you start assigning the issues

**Comment by atharvarekhawar** [comment]
@dhruvpatidar359 is there any contribution guide for creating PR

**Comment by dhruvpatidar359** [comment]
> @dhruvpatidar359 is there any contribution guide for creating PR

Hi @atharvarekhawar  , i have modified the readme.md , you may check there . While you create PR you will get the type of PR there itself . If you have any doubt regarding installation you may ask . 

I will be creating a video on the installation soon, don't worry . Till then try to install using the updated readme
