### ISSUE TITLE
Eraser is missing

### ISSUE THREAD

**Issue by dhruvpatidar359** [dhruvpatidar359/nextdraw#2]
- [✅ ] Tried NextDraw ?

What is Currently present in the nextdraw :
1 ) Only delete button works for deleting the selected element.

### Features:

There is no Eraser present in Nextdraw yet. 

![image](https://github.com/dhruvpatidar359/nextdraw/assets/103873587/9f66fd79-3746-4631-b18c-e16abb8e525a)

Guide : 
Eraser can be created by just detecing if there are elements present below the mouse pointer or not . If they are there , we can delete the  elements , which are detected by the mouse . 
1 ) We can use getElementBelow() function  to get the below element which is present in Element.js file.
2 ) Now you can remove the element .

**Comment by Shobhit-Nagpal** [comment]
hey dhruv! would love to work on this issue under gssoc' 24, seems interesting :)

**Comment by riyasaxena32** [comment]
please assign this issue to I will add eraser functionality in this white board

**Comment by Shobhit-Nagpal** [comment]
hey. i am done with the main eraser functionality. currently, i'm adding the eraser icon to the circular tool bar.

i was wondering if you used any tool to generate the positions of the tools in the tool bar?

once this is sorted, i'll send over a pr for this issue.

**Comment by dhruvpatidar359** [comment]
> hey. i am done with the main eraser functionality. currently, i'm adding the eraser icon to the circular tool bar.
> 
> i was wondering if you used any tool to generate the positions of the tools in the tool bar?
> 
> once this is sorted, i'll send over a pr for this issue.

may you please explain what do mean by the positions of the tools , are you saying where to put the eraser button in this ? 
- > If this is so you may place it after the text feature .



Thanks 
- Dhruv

**Comment by Shobhit-Nagpal** [comment]
> > hey. i am done with the main eraser functionality. currently, i'm adding the eraser icon to the circular tool bar.
> > i was wondering if you used any tool to generate the positions of the tools in the tool bar?
> > once this is sorted, i'll send over a pr for this issue.
> 
> may you please explain what do mean by the positions of the tools , are you saying where to put the eraser button in this ?
> 
> * > If this is so you may place it after the text feature .
> 
> Thanks
> 
> * Dhruv

by position, i meant the d attribute on the path tag for the tools. Attaching screenshot below:

![image](https://github.com/dhruvpatidar359/nextdraw/assets/74096450/dc2bfbef-6b35-4f3a-90ce-0c0873c02732)

was wondering if you used any tool to determine the d's to accurately position the tools in a circular position.

i did some hit and trial and added the eraser tool, opened a pr as well. although it's not after the text tool. you want me to make the changes and update you?

**Comment by dhruvpatidar359** [comment]
> > > hey. i am done with the main eraser functionality. currently, i'm adding the eraser icon to the circular tool bar.
> > > i was wondering if you used any tool to generate the positions of the tools in the tool bar?
> > > once this is sorted, i'll send over a pr for this issue.
> > 
> > 
> > may you please explain what do mean by the positions of the tools , are you saying where to put the eraser button in this ?
> > 
> > * > If this is so you may place it after the text feature .
> > 
> > Thanks
> > 
> > * Dhruv
> 
> by position, i meant the d attribute on the path tag for the tools. Attaching screenshot below:
> 
> ![image](https://private-user-images.githubusercontent.com/74096450/329755962-dc2bfbef-6b35-4f3a-90ce-0c0873c02732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NzczNTUsIm5iZiI6MTcxNTQ3NzA1NSwicGF0aCI6Ii83NDA5NjQ1MC8zMjk3NTU5NjItZGMyYmZiZWYtNmIzNS00ZjNhLTkwY2UtMGMwODczYzAyNzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAxMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0OGQ1ZmVhZDhkZWI1Nzc5MzkxMDRmYjM5MmUwYmI2MzhlYzFjMmQyNzI2NWNkYjc0Nzk5MGEwODc1NzQ5YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G3B0L2diD56fGlEb23zKxkCDt4vMkbgeIF-XKJq0c8s)
> 
> was wondering if you used any tool to determine the d's to accurately position the tools in a circular position.
> 
> i did some hit and trial and added the eraser tool, opened a pr as well. although it's not after the text tool. you want me to make the changes and update you?

actually it did not used any tool for that , i was in  bit hurry to create this stuff . Thanks for your patience to adjust it 🔧. I know the pain .

**Comment by Shobhit-Nagpal** [comment]
haha, i enjoyed working on this. thanks for assigning the issue
