### ISSUE TITLE
Adding a sign up feature

### ISSUE THREAD

**Issue by Souvik34** [dhruvpatidar359/nextdraw#20]
**Is your feature request related to a problem? Please describe.**
Lack of sign in and sign up feature

**Describe the solution you'd like**
There will be a sign in feature

**Describe alternatives you've considered**

**Additional context**
Assign me the task

**Comment by dhruvpatidar359** [comment]
@Souvik34  may you please quote down the reasons for creating a  sign up and sign in features . May you please clarify it more.
Thanks - Dhruv
