### ISSUE TITLE
large dockerfile size

### ISSUE THREAD

**Issue by Bhavya-55** [dhruvpatidar359/nextdraw#23]
**Describe the bug**
Dockerfile size is too large for the prokeject its 2.23 Gb it needs to be reduced for less build time and optimisation

**To Reproduce**
build the image using cmd docker build . -t image-name
and then check size ..

**Expected behavior**
we should alter dockerfile to change itssize

**Screenshots**

![Screenshot 2024-05-11 135724](https://github.com/dhruvpatidar359/nextdraw/assets/121238674/36c685a6-9ba3-46fd-a70d-810ff0306f41)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bhavya-55** [comment]
@dhruvpatidar359 I can update this dockerfile and reduce to to 1.25 gb . i have worked already on this

**Comment by dhruvpatidar359** [comment]
sure , go ahead . Assigning to you
