### ISSUE TITLE
[FEATURE] Implement Keyboard Shortcut to Delete Drawing on Screen

### ISSUE THREAD

**Issue by yashmandi** [dhruvpatidar359/nextdraw#44]
**Feature Description**
I have worked with similar drawing sites, and when I draw something and I want to delete / erase something, I have the habit of selecting it by mouse and delete / erase it using 'DELETE' button on my keyboard. This feature would be helpful for many people.

**Solution*
When someone wants to delete / erase the drawing, they can simply select it using mouse and press delete button on keyboard.
I would like to work on this issue under GSSoC '24, request you to assign this task to me :)

**Comment by dhruvpatidar359** [comment]
Hi @yashmandi  thanks for opening an issue. 
This is already implemented in the code , the problem right now is , it has been breaked by a PR , we are right now trying to resolve it . If you can resolve it , here is the PR that breaked it , i have also commented down in the PR itself. #41
