### ISSUE TITLE
Enhance Readme.md  file 

### ISSUE THREAD

**Issue by aasthakourav20** [dhruvpatidar359/nextdraw#53]
Hey @dhruvpatidar359 , A Readme file plays an important role in User/Contributor convenience . It is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers.
Let's create a more descriptive , attention seeking README file including all guidelines .

Kindly assign this issue to me under GSSoC'24 .

**Comment by dhruvpatidar359** [comment]
Hey @aasthakourav20 , may you please describe the steps or the things that you are gonna inlcude in details .👩‍🚀

**Comment by aasthakourav20** [comment]
> Hey @aasthakourav20 , may you please describe the steps or the things that you are gonna include in details .👩‍🚀

Hey @dhruvpatidar359 , we can just add more description about what the project actually is and can add certain detailed guidelines for the user/Contributors . Will help the contributors about the project in a single run.

**Comment by dhruvpatidar359** [comment]
> > Hey @aasthakourav20 , may you please describe the steps or the things that you are gonna include in details .👩‍🚀
> 
> Hey @dhruvpatidar359 , we can just add more description about what the project actually is and can add certain detailed guidelines for the user/Contributors . Will help the contributors about the project in a single run.

alright , then please make a PR to modify the ReadMe.md that looks good . Go ahead , will assign this issue , first please show some work on this . As we are not clear about what things you are gonna include .
