### ISSUE TITLE
[GSSoC'24]Eraser 

### ISSUE THREAD

**Issue by Apurv7777** [dhruvpatidar359/nextdraw#64]
**Describe the bug**
Eraser is behind the drawing and sometimes not able to remove drawings.

**Expected behavior**
Eraser must be properly visible on drawings .

**Screenshots**
- Not able to take screenshot of that .
 
**Desktop (please complete the following information):**
- Chrome

I am willing to work on this.

**Comment by dhruvpatidar359** [comment]
@Apurv7777  Hi , may you please give us screenshot of that .

**Comment by Apurv7777** [comment]
![nextdraw](https://github.com/dhruvpatidar359/nextdraw/assets/65327303/01b38df8-668e-42f1-b13f-bd3bfaea5d44)

**Comment by dhruvpatidar359** [comment]
@Apurv7777  alright got your point . Go ahead 👩‍🚀 , assigning you .
