### ISSUE TITLE
Already exist project 

### ISSUE THREAD

**Issue by devaniketh** [dhruvpatidar359/nextdraw#69]
My simple answer is this if there exist better product like app.eraser.io and excail draw why would i even look to your project 
convince me that this project is better than those two mentioned above

**Comment by dhruvpatidar359** [comment]
@AnikethDeb2004  you said absolutely right . First of all this project is to understand how this big things work . The uniqueness of the project is second thing . We are here to make people understand what is open source really . Not just make to work as a single person , but working in a team . There is no need to convince , it is upto you , whether you want to dive into this niche and learn how things work . 

You may even compare the code bases , our code is small enough to understand . Well the choice is yours . We are not bounding you . 

We love opensource , and we spread it  . That's simple 👩‍🚀

**Comment by dhruvpatidar359** [comment]
I am closing it , if you want to discuss more , you may repopen this .
