### ISSUE TITLE
Add Pan option using the space button on Desktop

### ISSUE THREAD

**Issue by dhruvpatidar359** [dhruvpatidar359/nextdraw#7]
**Is your feature request related to a problem? Please describe.**
Currently the devices with touch pad can only pan .

![image](https://github.com/dhruvpatidar359/nextdraw/assets/103873587/65966b16-e4ae-4ff1-8690-a4ee525e6f42)

**Describe the solution you'd like**
Use keyboard space button and mouse move on it to pan the canvas.

**Additional context**
Files like : Canvas.jsx contains the code for panning .

**Comment by a-khushal** [comment]
@dhruvpatidar359 can I work on this issue?

**Comment by dhruvpatidar359** [comment]
sure , please go ahead
