### ISSUE TITLE
Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [dhruvpatidar359/nextdraw#79]
**Please describe your feature.**
A preloader is an essential feature for enhancing user experience by indicating the progress of loading content. It helps in keeping the users engaged while the main content is being fetched or rendered. Implementing a preloader can significantly improve the perceived performance of our application.

**Describe the solution you'd like**
**Design and Appearance:**
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

**Functionality:**
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

**Performance:**
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

**Implementation:**
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

**Additional context**
My Previous Work:-
https://github.com/dhruvpatidar359/nextdraw/assets/146121869/39bf7e74-7f2d-49f2-88ac-a67545094678

**Comment by dhruvpatidar359** [comment]
Hi @AsmitaMishra24  , we already have the perloader on our webapp . Please make sure to not to raise issue , if it is already present .
